### ISSUE TITLE
Max Prioritiy for new transitions

### ISSUE THREAD

**Issue by ankeshanand** [astooke/rlpyt#102]
The Rainbow paper says: 
> New transitions are inserted into the replay buffer with maximum priority, providing a bias towards recent transitions.

In the prioritized replay buffer implementation in the repo though, it seems new samples are set to a default priority of 1. Is there a way to set the priorities of all incoming transitions to be the max priority in the tree?

**Comment by astooke** [comment]
Hi!  Good question, this doesn't exist yet, but easily be implemented.  In the ``update_batch_priorities()`` method:

https://github.com/astooke/rlpyt/blob/d797dd8835a91a7b2902563a097c83ed7c8d3e92/rlpyt/replays/sum_tree.py#L130

could add a line like ``self.default_priority = max(priorities)``

And ``self.default_priority`` gets used for new samples here:

https://github.com/astooke/rlpyt/blob/d797dd8835a91a7b2902563a097c83ed7c8d3e92/rlpyt/replays/sum_tree.py#L164

However in Rainbow, using the Huber loss, it caps the TD-error at 1, so 1 should actually remain the max priority in that case.

**Comment by ankeshanand** [comment]
Thanks, this should work for the most part. This would update priorities only after training has started though right? Is there a way to make this work when samples are appended into the buffer?

**Comment by astooke** [comment]
That's correct.  And yes, it is possible to also feed priorities into the replay buffer along with the samples.  The one implemented algorithm which does this is R2D1, see this line:

https://github.com/astooke/rlpyt/blob/d797dd8835a91a7b2902563a097c83ed7c8d3e92/rlpyt/algos/dqn/r2d1.py#L148

And check out other lines to do with the replay buffer in that file, for example when you instantiate the replay buffer you have to tell it that you will feed in the priorities, because it has to set up some caching.

That example is a bit complicated but hopefully the pieces are well-described in the documentation now :)
