### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by jordan-schneider** [astooke/rlpyt#120]
Is there a guide to contributing somewhere? At the very least it would be nice to know what formatters/linters y'all are using.

If there isn't a standard formatter or linter, could I recommend black for formatting, and pylint + mypy for linting?

**Comment by astooke** [comment]
Good question!  I had I think pylinter in sublimetext3 before, and now I'm on a new machine and don't have quite the same settings, urgh.  Is there a way to link a linter to pull requests, you're saying?

**Comment by jordan-schneider** [comment]
I was just asking for a text document that described how to make contributions that included what tools were being used, and with what settings.

If you wanted to go full software-engineering on the problem, you could setup a CI pipeline that required PRs to pass lint and etc before they're allowed to be merged. I've never tried to do that, and have no idea how much work it is. Maybe look at https://help.github.com/en/github/administering-a-repository/about-required-status-checks and https://developer.github.com/apps/quickstart-guides/creating-ci-tests-with-the-checks-api/ for details.

But really I just want like, a requirements.txt file that contains the formatter and linter you use, and the configuration files for those formatters and linters.

**Comment by juliusfrost** [comment]
Hi guys, I went ahead of myself to implement a bunch of testing features. See my pull request: #133 
We could build the contribution guides around this. 
To explain my reasoning behind certain choices:
I chose GitHub actions for testing as they have reliable windows instance testing, as compared to Travis (I got a lot of errors there). It was pretty straightforward to customize the build and try different versions of pytorch.
I chose to use PEP8 styling because it is very common in pip packages and recommended by the python community. I use PyCharm as my IDE and it is the default there.
I chose [codecov.io](https://codecov.io/) to host code coverage reports as it has the most features over competitors and is free. 
I added some basic requirements to the setup.py file as you don't need the requirements.txt one you have that.

**Comment by astooke** [comment]
@jordan-schneider OK good idea I can write up a short contribution guide.  As for formatting/linting, it's basically following pep8, for example via flake8 with defaults and just with one `ingore=E128` for indentations.  Something along those lines sound like what you're looking for?  

@juliusfrost Cool I like the idea of adding badges and github actions for testing.  Although obviously that's a gap in this repo now, the absence of any unit tests.  I just verified bits and pieces manually as I was building and then checked learning curves, kinda wish I had done a little better there, but after all it's a research project ;) .   Good idea tho to add a tests folder--can go back and populate that over time or definitely with new features.

Preference overall is to keep it as light-weight as possible and easy to keep up with.

**Comment by astooke** [comment]
Ok we have a basic contribution guide in place now, how does it look to you?  And we have some great tests and linting thanks to @juliusfrost!
