### ISSUE TITLE
Optimizing the game simulation

### ISSUE THREAD

**Issue by maxwellreuter** [astooke/rlpyt#167]
Is there room for improvement in the speed/memory efficiency of the simulation of the game? I'd like to make this aspect of training as fast as possible. If this seems possible and worthwhile, where and how would you recommend I start (ex. Cython)? Thanks!

**Comment by astooke** [comment]
Hi!  Do you mean the Atari emulator?  I've looked into this a little bit.  Within the emulator, the code is pretty serial, so there's no obvious boost from e.g. vectorizing math or anything.  So the best I could come up with was to 1) make sure the rlpyt env does as little extraneous work as possible, so all the time is in the emulator, (worst culprit to watch out for is slow resizing of the images) and 2) parallelize the sampling so that multiple serial emulators could run efficiently on multiple CPUs.  The alternating-parallel-gpu sampler is usually best for Atari...all the bells and whistles.

Nvidia recently ported Atari to run on GPU, though, and it's fast if you can run a LOT of environments in parallel.  I haven't tried it with rlpyt, but might be worth looking into:
https://news.developer.nvidia.com/new-open-source-gpu-accelerated-atari-emulator-for-reinforcement-learning-now-available/

Hope that helps!

**Comment by maxwellreuter** [comment]
Thank you!
