### ISSUE TITLE
SAC not working

### ISSUE THREAD

**Issue by kapsl** [astooke/rlpyt#32]
Hi,
I'm using the old softlearning environment and learning works great there. I now wanted to test your environment, but it does not work at all. I have the feeling that definitely one problem is, that for ~1 trial the robot performs good (big) exploration motions. Then the learner starts  - and the motion directly collapse to an almost 0 action, which makes it impossible to do exploration.

My configuration file is:

`
from iiwa_sim_fri import IiwaSimFri
from rlpyt.samplers.async_.cpu_sampler import AsyncCpuSampler
from rlpyt.samplers.async_.gpu_sampler import AsyncGpuSampler
from rlpyt.samplers.parallel.cpu.sampler import CpuSampler
from rlpyt.samplers.parallel.gpu.sampler import GpuSampler
from rlpyt.samplers.serial.sampler import SerialSampler
from rlpyt.envs.gym import make as gym_make, GymEnvWrapper
from rlpyt.algos.qpg.sac import SAC
from rlpyt.agents.qpg.sac_agent import SacAgent
from rlpyt.runners.minibatch_rl import MinibatchRlEval, MinibatchRl
from rlpyt.utils.logging.context import logger_context

def build_and_train(env_id="iiwa", run_ID=0, cuda_idx=None):
    n_parallel=3
    affinity = dict(cuda_idx=0, workers_cpus=list(range(n_parallel)))

    sampler = SerialSampler(
    # sampler = GpuSampler(
    # sampler = CpuSampler(
        # EnvCls=gym_make,
        EnvCls=make,
        #EnvCls=IiwaSimFri(hyperparams=get_hyperparams()),
        env_kwargs=dict(id=env_id),
        eval_env_kwargs=dict(id=env_id),
        batch_T=1,  # One time-step per sampler iteration.
        batch_B=1,  # One environment (i.e. sampler Batch dimension).
        max_decorrelation_steps=100,
        eval_n_envs=0,
        eval_max_steps=int(201),  # int(51e3),
        eval_max_trajectories=5,
    )
    algo = SAC(min_steps_learn=int(30 * 200),
               batch_size=1024,
               replay_ratio=256)  # Run with defaults.
    agent = SacAgent()
    # runner = MinibatchRlEval(
    runner = MinibatchRl(
        algo=algo,
        agent=agent,
        sampler=sampler,
        n_steps=1e6,
        log_interval_steps=10,
        affinity=affinity,
    )
    config = dict(env_id=env_id)
    name = "sac_" + env_id
    log_dir = "example_1"
    with logger_context(log_dir, run_ID, name, config):
        runner.train()
def make(*args, info_example=None, **kwargs):
    hyperparams = get_hyperparams()

    return GymEnvWrapper(IiwaSimFri(hyperparams=hyperparams))
`

**Comment by kapsl** [comment]
Same with td3. Is it possible that the algorithms do just output actions in [0, 1] and they have to be scaled up manually to action_space?

**Comment by astooke** [comment]
Hi!  I'm not familiar with your environment, but possibly your `min_steps_learn` is too small, or your `learning_rate` is too large?  

With `replay_ratio=256`, but `batch_size=1024`, it should only update the NN once every 4 steps gathered, so you would change `batch_T=4`.  When you run, what message is printed about "updates per optimize"?  Probably 1?

I think the agents are currently set for action outputs in symmetric ranges, like [-1, 1] (for example SAC tanh squashing does this).

With these algorithms, it's probably better to use `MinibatchRlEval`, so that you can change the policy noise during evaluation.

**Comment by kapsl** [comment]
When rescaling the actions, the motions seem ok. I changed to replay_ratio=256 and batch_size=256 and batch_T=1 but there is still no learning progress. It sayis optimizing over 10 iterations. And it says Computed 1 updates per iteration.

**Comment by astooke** [comment]
OK, you probably need a larger `log_interval_steps`.  10 is very small (doing an evaluation run every 10 environment steps).  I would probably use something like 1e4 there, if your total `n_steps` is 1e6.  Maybe then the program will proceed faster.  

Otherwise, if it's not learning, I can't really speculate why, I don't have experience with this environment?

**Comment by astooke** [comment]
Any news or new questions here? If not, we can close this issue?

**Comment by astooke** [comment]
Feel free to reopen if the questions weren't answered. :)
