### ISSUE TITLE
serial/sampler obtain_samples() return self.samples.pyt, not self.samples.np

### ISSUE THREAD

**Issue by Lhyejin** [astooke/rlpyt#45]
Why obtain_sampels() return self.samples.pyt, not self.samples.np? 
when self.collector.collect_batch() called , output values store in (agent_buf, env_buf)  of self.sample_np. 
Are self.sample_np and self.sampler_pyt interlinked internally in the serial sampler? If then, when output value is stored in self.sample_np,  does self.sample_pyt immediately save torchfied output values?

**Comment by astooke** [comment]
yes those buffers refer to the same underlying memory.  one is in the form of torch tensors, which is returned so that the algorithm can use them.  the other one is in the form of numpy arrays, which are sometimes used for writing into or may otherwise be useful.

**Comment by Lhyejin** [comment]
thank you:) ans sorry but I ask to you one thing. the reason I asked that, I am doing customizing for multi-agent under a certain enviroment not gym(wrapping gym). but In the process of fixing it, I found that  empty sample_pyt initialized in samples/buffer was used in optimize_agent. so I only used sample_np Is there any problem with that? and where is the code that sample_np value is allocated to sample_pyt?, when collect_batch() called?

**Comment by astooke** [comment]
Hmm, yes samples_pyt and samples_np are built at the beginning, both refer to the same memory, and should only be written to by index (e.g. `samples.observation[:] = xx`), so that the objects remain intact.  So at every iteration the sampler returns the same object `samples_pyt`, which should hold the data written into `samples_np` during sampling.  

(All the algorithms are written in PyTorch, so you'll need to feed them torch tensors.  You can write data from torch tensors into numpy arrays, but it didn't always work when i tried to write data from numpy arrays into torch tensors.)

**Comment by Lhyejin** [comment]
thank you! It was very helpful.
