### ISSUE TITLE
"no GPU AssertionError" should not be raised?

### ISSUE THREAD

**Issue by codelast** [astooke/rlpyt#54]
Hi, I follow the doc and install rlpyt via the linux_cpu.yml configuration file, and then I try to run an example:

> python atari_dqn_async_cpu.py

which then gives me an AssertionError during the training process:
> AssertionError: 
> Found no NVIDIA driver on your system. Please check that you
> have an NVIDIA GPU and installed a driver from
> http://www.nvidia.com/Download/index.aspx

I think this might cause some confusion because I installed a CPU version rlpyt.

**Comment by astooke** [comment]
Hi!  Yes, sorry, that is confusing from the name of the file.  The name refers to the fact that it's using the CPU sampler, rather than the GPU sampler.   Check inside the file and see that it has `n_gpu` greater than 0.  (Async code only makes sense with GPUs anyway, because the point is to keep the GPUs and CPUs all busy at the same time.)

**Comment by codelast** [comment]
Thanks for clarifying that.
