### ISSUE TITLE
customized environment example?

### ISSUE THREAD

**Issue by sufengniu** [astooke/rlpyt#71]
Hello, I wonder if there is any customized environment examples? since I tried to create one, but found a lot of limitations here: 
1. I found that the environment info must only be boolean or number, if I the environment info contains text, then the code would stucked on utils/buffer.py build_array function (which use np.zeros for constructor), anyone can confirm this issue, or is there anyway to avoid it?
2. if I have multiple action types, let's say I have a self-driving car agent which might have steer, brake, accelerate, (three actions). is the best way for environment is create namedtuple? would it cause any problems on samplers or elsewhere?
3. state: sometime we have very complicated state, that state cannot be concatenated together as a tensor, (let's say state contains both image, and some feature vector), what is the best way to pass the state? I found dictionary would be blocked by utils.buffer.py. How can I overcome this?

Thank you

**Comment by bmazoure** [comment]
I believe you can just wrap your OpenAI gym env in https://github.com/astooke/rlpyt/blob/master/rlpyt/envs/gym.py#L13 this class?

**Comment by sufengniu** [comment]
hmm... I haven't found this wrapper before, will try it, thank you, will try this again

**Comment by astooke** [comment]
Hi!  Some more comments on your questions:

1. Yes everything in the env_info needs to be able to become numpy arrays, and stay the same shape at every time step.  This is because there are fixed buffers for the info which are allocated ahead of time, so they can use shared memory for instant communication between parallel processes.  If you need more flexibility here, you could modify the sampler + collector to do something different with the env_info (easiest in serial case where everything stays in one process).

2. For these actions you could create an `IntBox` action space just like the one in the atari env which is included, for a discrete set of actions.

3. Yes, this is intended to be possible :)  You can create a separate space for each kind of observation, and then combine them into a `Composite` space, and make that the observation space of the environment.  Alternatively, if you have a gym-style environment, then the gym-space wrapper in the example will try to convert a gym-dict space into an rlpyt-composite space automatically.  (The composite space uses namedtuples for organizing the sub-spaces, so that all the namedarraytuple machinery works with it.)

Hope this helps!

**Comment by sufengniu** [comment]
@astooke thank you! I did try to use GymEnvWrapper, all I did is very simple as following:
```
env = MyEnv()
    sampler = SerialSampler(
        EnvCls=GymEnvWrapper(env),
        env_kwargs=dict(state_type="smol"), # any environment statement you want to modify put here
        eval_env_kwargs=dict(state_type="smol"),
        batch_T=4,  # Four time-steps per sampler iteration.
        batch_B=1,
        max_decorrelation_steps=0,
        eval_n_envs=10,
        eval_max_steps=int(10e3),
        eval_max_trajectories=5,
    )
```
and my input action is dictionary, the observation is also a dictionary, when I run my code, I got following error:

>   File "examples/example_test.py", line 50, in build_and_train
>     runner.train()
>   File "/home/sniu/lab/ai_lab/rlpyt/examples/../rlpyt/runners/minibatch_rl.py", line 229, in train
>     n_itr = self.startup()
>   File "/home/sniu/lab/ai_lab/rlpyt/examples/../rlpyt/runners/minibatch_rl.py", line 61, in startup
>     world_size=world_size,
>   File "/home/sniu/lab/ai_lab/rlpyt/examples/../rlpyt/samplers/serial/sampler.py", line 31, in initialize
>     envs = [self.EnvCls(**self.env_kwargs) for _ in range(B)]
>   File "/home/sniu/lab/ai_lab/rlpyt/examples/../rlpyt/samplers/serial/sampler.py", line 31, in <listcomp>
>     envs = [self.EnvCls(**self.env_kwargs) for _ in range(B)]
> TypeError: 'GymEnvWrapper' object is not callable

I checked the sampler.py line 31, self.EnvCls is <GymEnvWrapper<MyEnv instance>>, and self.env_kwargs is also expected. Do you know where the problem might be? or I miss utilize the GymEnvWrapper? Thank you!

**Comment by astooke** [comment]
I see, you almost have it working!  

The EnvCls needs to be the class type (or a factory function) which returns a class instance, and it needs to be a totally separate object from other env instances.  So in your case you would write a function which looks like the `make` function from envs/gym.py:

```python
def make_env(*args, **kwargs):
  return GymEnvWrapper(MyEnv(*args, **kwargs))
```
and then pass `EnvCls=make_env` and the `env_kwargs` just as you have it.

Give that a try?

**Comment by sufengniu** [comment]
Thank you! that works
