### ISSUE TITLE
Consequences of Imprecise Space Definition?

### ISSUE THREAD

**Issue by bpiv400** [astooke/rlpyt#80]
Hi Adam, 

I'm working with a custom environment with a fairly complex observation space. There are over 500 features in the observation space that consist of a mixture of 0-1 indicators, bounded integers, unbounded integers, bounded reals, and unbounded reals. As a result, I'm not keen on creating a very large, complex Composite space to precisely reflect all the constraints. I'd rather just use a FloatBox with large bounds. 

Are there any consequences in rlpyt to this imprecise implementation that I might not be aware of? (I have no intention of using any kind of Sampler with random starts, and my environment ensures that given a legal observation, the next observation will also be legal. ) 

Separately, the code base feels a little under documented, especially for users who are creating custom environments from scratch. I'm wondering if you'd be interested in me providing additional documentation / a usage guide as I progress through my project. 

Thanks again for providing this resource.

**Comment by codelast** [comment]
> Separately, the code base feels a little under documented, especially for users who are creating custom environments from scratch.

Couldn't agree more. It needs quite a lot of efforts to understand the source code.

**Comment by astooke** [comment]
Hi!  Thanks for your question!  I see your point about not wanting to bother constructing some complicated space.   The only thing I can think of is where you might use `space.sample()`, it would return some invalid value.  So I think you're right that as long as you don't use the random starts, nothing else in rlpyt will use this method to populate any data.

One other thing you might want to double check is what happens if the action values are all populated with zero.  If you have a recurrent agent, this might get fed in as the `prev_action` for the first step in a new episode.  But you can specify the `space.null_value()` to return exactly what you want for this.  The samplers currently just assign `prev_action[:]=0` instead of `prev_action[:]=env.action_space.null_value()`, so would need to change that.

I hear you on the documentation...working on that now :)  No telling how long that will take, but will try to at least get a draft up asap.
