### ISSUE TITLE
DQN algo: samples.action requires squeeze

### ISSUE THREAD

**Issue by kolbytn** [astooke/rlpyt#95]
I'm running `example_1.py` with a custom Environment and the `DqnAgent` class with a custom Model Class. I get the following error in `DQN` the first time `DQN.loss` is called.

```Traceback (most recent call last):
  File "main.py", line 131, in <module>
    train_toy_dqn("toy_dqn_test")
  File "main.py", line 54, in train_toy_dqn
    runner.train()
  File "/mnt/pccfs/backed_up/kolby/morl-rlpyt/venv/lib/python3.6/site-packages/rlpyt/runners/minibatch_rl.py", line 240, in train
    opt_info = self.algo.optimize_agent(itr, samples)
  File "/mnt/pccfs/backed_up/kolby/morl-rlpyt/algo/dqn.py", line 149, in optimize_agent
    loss, td_abs_errors = self.loss(samples_from_replay)
  File "/mnt/pccfs/backed_up/kolby/morl-rlpyt/algo/dqn.py", line 176, in loss
    q = select_at_indexes(samples.action, qs)
  File "/mnt/pccfs/backed_up/kolby/morl-rlpyt/venv/lib/python3.6/site-packages/rlpyt/utils/tensor.py", line 8, in select_at_indexes
    assert indexes.shape == tensor.shape[:dim]
AssertionError
```

The shapes of `sameples.action` and `qs` are `(32,1)` and `(32,4)` respectively. If I squeeze `samples.action` down to `(32)` the error goes away. I'm trying to find what causes the shape miss match in my code. I assumed it had to do with my environment's action space, but I've been unable to find a fix. My environment's action space is defined as `self._action_space = IntBox(low=0, high=4, shape=())`.

How should the action space be defined for an environment with a discrete action space?

**Comment by astooke** [comment]
Hmm that looks like an OK way to define the action space, just like is done in the AtariEnv, although there it doesn't receive an argument for the `shape`, it should replace `None` with `()` anyway.  But try without that argument?  I'm surprised that `samples.action` is shaped `(32, 1)`, I tried to trim off extra dimensions like that everywhere.

Oh, are you sure that your `env.action_space.sample()` puts out a numpy array which is a scalar, i.e. `env.action_space.sample().shape==()`?  If a dimension `(1,)` sneaks in there, that would appear in the `samples.action.shape`.

**Comment by kolbytn** [comment]
I still see the error without explicitly passing in the shape, and the shape of what I sample from my action space is `()`. Should I perhaps be squeezing the output of my network? Right now it outputs `(Batch x Actions)` even when `Batch=1`.

**Comment by astooke** [comment]
Yes, good call, should squeeze in the model.  All the built-in models use this shape inference to have their output leading dimensions match those of the inputs, so if your agent doesn't receive a batch dimension, it should not output a batch dimension.  Example in the DQN model:
https://github.com/astooke/rlpyt/blob/75e96cda433626868fd2a30058be67b99bbad810/rlpyt/models/dqn/atari_dqn_model.py#L54

Indeed the allocated shape of `samples.action` is based on an example action returned from `agent.step()` based on an input observation with no leading dimensions, so that would be where the extra dimension came from.  

Sorry that took a while to dig into!  Work on documentation is underway, could hopefully have cleared that up ahead of time.

Let us know if it fixes?

**Comment by kolbytn** [comment]
I'm using the `infer_leading_dims`, and `restore_leading_dims` methods and everything seems to be working now :+1:.
